# Generated by Django 6.0.3 on 2026-03-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_remove_actor_actor_name_af_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_name_ky',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='bio_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='country',
            name='country_name_ky',
        ),
        migrations.RemoveField(
            model_name='director',
            name='bio_ky',
        ),
        migrations.RemoveField(
            model_name='director',
            name='director_name_ky',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='Genre_name_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_name_ky',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='slogan_ky',
        ),
        migrations.RemoveField(
            model_name='movielanguages',
            name='language_ky',
        ),
    ]
